name: test
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  github-context:
    name: context
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:1.12
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        run: make setup
      - name: test
        env:
          RICHGO_LOCAL: 1
        run: make test
      - run: richgo test -v -cover -race ./...
