name: test
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  github-context:
    name: context
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    container:
      image: golang:1.12
    steps:
      - uses: actions/checkout@master
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:1.12
    steps:
      - run: "ls -al"
      - name: setup
        run: make setup
      - name: test
        run: make test
