name: test
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:1.12
    steps:
      - run: make setup
      - run: make test
